-- =============================================================
-- 152_site_settings_offer_pdf_labels.sql
-- Ensotek – Offer PDF Labels (site_settings.offer_pdf_labels)
--  - Value: JSON (stored as TEXT)
--  - Localized: tr / en / de
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

INSERT INTO site_settings (id, `key`, locale, `value`, created_at, updated_at) VALUES
(
  UUID(),
  'offer_pdf_labels',
  'tr',
  CAST(JSON_OBJECT(
    'title',                   'Teklif',
    'quoteNo',                 'Teklif No',
    'date',                    'Tarih',
    'validity',                'Geçerlilik',
    'status',                  'Durum',

    'customerInfo',            'Müşteri Bilgileri',
    'name',                    'Ad Soyad',
    'company',                 'Firma',
    'email',                   'E-posta',
    'phone',                   'Telefon',
    'country',                 'Ülke',
    'formLanguage',            'Form dili',
    'product',                 'Ürün',
    'service',                 'Hizmet',

    'summary',                 'Teklif Özeti',
    'subject',                 'Konu',
    'noMessage',               'Müşteri mesajı bulunmamaktadır.',

    'pricing',                 'Fiyatlandırma',
    'net',                     'Net Tutar',
    'vat',                     'KDV',
    'shipping',                'Nakliye',
    'total',                   'Genel Toplam',
    'pricingEmpty',            'Fiyatlandırma henüz eklenmemiştir; bu belge ön teklif niteliğindedir.',

    'notes',                   'Notlar',

    'notesLegalTemplate',      'Bu belge bilgilendirme amaçlıdır. Nihai fiyat ve ticari koşullar, {{validUntilPart}}Ensotek tarafından yazılı olarak onaylandığında geçerli olacaktır.',
    'validUntilPartTemplate',  '{{validUntil}} tarihine kadar geçerli olup ',
    'internalNotes',           'İdari not (dahili kullanım)',

    'footerLeftTemplate',      '{{siteName}} – Otomatik Teklif Sistemi',
    'footerRight',             'Bu PDF sistem tarafından oluşturulmuştur, imza gerektirmez.'
  ) AS CHAR),
  NOW(3),
  NOW(3)
),
(
  UUID(),
  'offer_pdf_labels',
  'en',
  CAST(JSON_OBJECT(
    'title',                   'Offer',
    'quoteNo',                 'Offer No',
    'date',                    'Date',
    'validity',                'Valid Until',
    'status',                  'Status',

    'customerInfo',            'Customer Information',
    'name',                    'Name',
    'company',                 'Company',
    'email',                   'Email',
    'phone',                   'Phone',
    'country',                 'Country',
    'formLanguage',            'Form language',
    'product',                 'Product',
    'service',                 'Service',

    'summary',                 'Offer Summary',
    'subject',                 'Subject',
    'noMessage',               'No customer message has been provided.',

    'pricing',                 'Pricing',
    'net',                     'Net Amount',
    'vat',                     'VAT',
    'shipping',                'Shipping',
    'total',                   'Grand Total',
    'pricingEmpty',            'Pricing has not been added yet; this document should be considered a preliminary offer.',

    'notes',                   'Notes',

    'notesLegalTemplate',      'This document is for information purposes only. Final prices and commercial terms become valid only after written confirmation by Ensotek{{validUntilPart}}.',
    'validUntilPartTemplate',  ' and are valid until {{validUntil}}',
    'internalNotes',           'Internal note',

    'footerLeftTemplate',      '{{siteName}} – Automated Offer System',
    'footerRight',             'This PDF is generated by the system and does not require a signature.'
  ) AS CHAR),
  NOW(3),
  NOW(3)
),
(
  UUID(),
  'offer_pdf_labels',
  'de',
  CAST(JSON_OBJECT(
    'title',                   'Angebot',
    'quoteNo',                 'Angebots-Nr.',
    'date',                    'Datum',
    'validity',                'Gültig bis',
    'status',                  'Status',

    'customerInfo',            'Kundendaten',
    'name',                    'Name',
    'company',                 'Firma',
    'email',                   'E-Mail',
    'phone',                   'Telefon',
    'country',                 'Land',
    'formLanguage',            'Formularsprache',
    'product',                 'Produkt',
    'service',                 'Leistung',

    'summary',                 'Angebotsübersicht',
    'subject',                 'Betreff',
    'noMessage',               'Es wurde keine Kundenmitteilung angegeben.',

    'pricing',                 'Preisübersicht',
    'net',                     'Nettobetrag',
    'vat',                     'MwSt.',
    'shipping',                'Versand',
    'total',                   'Gesamtbetrag',
    'pricingEmpty',            'Preise wurden noch nicht hinterlegt; dieses Dokument ist ein unverbindlicher Vorab-Entwurf.',

    'notes',                   'Hinweise',

    'notesLegalTemplate',      'Dieses Dokument dient ausschließlich Informationszwecken. Endgültige Preise und Konditionen gelten erst nach schriftlicher Bestätigung durch Ensotek{{validUntilPart}}.',
    'validUntilPartTemplate',  ' und sind bis zum {{validUntil}} gültig',
    'internalNotes',           'Interne Notiz',

    'footerLeftTemplate',      '{{siteName}} – Automatisiertes Angebotssystem',
    'footerRight',             'Dieses PDF wurde automatisch erstellt und benötigt keine Unterschrift.'
  ) AS CHAR),
  NOW(3),
  NOW(3)
)
ON DUPLICATE KEY UPDATE
  `value`      = VALUES(`value`),
  `updated_at` = VALUES(`updated_at`);
